version: '3.4'

services:
  manga.webapi:
    container_name: WebApiContainer
    image: ${DOCKER_REGISTRY-}mangawebapi
    ports:
        - 8001:80
    build:
      context: .
      dockerfile: src/Manga.WebAPI/Dockerfile
    depends_on:
        - SqlServerDb
  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    ports:
      - "8002:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin123 
    volumes:
      - ./sql_data:/var/opt/mssql

volumes:
  sql_data: